# Generated by Django 2.1.2 on 2020-01-01 12:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Apartment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aptNumber', models.CharField(blank=True, default='', max_length=4, null=True)),
                ('size', models.CharField(choices=[('1', '3.5'), ('2', '4.5'), ('3', '5.5')], default='1', max_length=3)),
                ('status', models.CharField(choices=[('D', 'Disponible'), ('ND', 'Non disponible')], default='D', max_length=10)),
                ('description', models.CharField(blank=True, default='', max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('description', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('numberApts', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('address', models.CharField(max_length=30)),
                ('city', models.CharField(max_length=30)),
                ('postal', models.CharField(max_length=30)),
            ],
        ),
        migrations.AddField(
            model_name='apartment',
            name='property',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='pages.Property'),
        ),
    ]
