# Generated by Django 2.1.2 on 2020-01-02 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_auto_20200101_1240'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='image',
            field=models.ImageField(default='', upload_to='images/'),
        ),
    ]
