# Generated by Django 2.1.2 on 2020-01-09 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0009_auto_20200103_1536'),
    ]

    operations = [
        migrations.AddField(
            model_name='apartment',
            name='sizes',
            field=models.CharField(choices=[('1', '3.5'), ('2', '4.5'), ('3', '5.5')], default='1', max_length=3),
        ),
    ]
