# Generated by Django 2.1.2 on 2020-01-12 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0010_apartment_sizes'),
    ]

    operations = [
        migrations.CreateModel(
            name='TypeService',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('type1', models.CharField(max_length=40)),
                ('type2', models.CharField(max_length=40)),
                ('type3', models.CharField(max_length=40)),
                ('type4', models.CharField(max_length=40)),
            ],
        ),
    ]
