# Generated by Django 2.1.2 on 2020-01-12 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0012_auto_20200112_1338'),
    ]

    operations = [
        migrations.AlterField(
            model_name='typeservice',
            name='type1',
            field=models.CharField(blank=True, default='', max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='typeservice',
            name='type2',
            field=models.CharField(blank=True, default='', max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='typeservice',
            name='type3',
            field=models.CharField(blank=True, default='', max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='typeservice',
            name='type4',
            field=models.CharField(blank=True, default='', max_length=40, null=True),
        ),
    ]
