# Generated by Django 2.1.2 on 2020-01-14 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0013_auto_20200112_1344'),
    ]

    operations = [
        migrations.AddField(
            model_name='apartment',
            name='image1Text',
            field=models.CharField(blank=True, default='', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='apartment',
            name='image2Text',
            field=models.CharField(blank=True, default='', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='apartment',
            name='image3Text',
            field=models.CharField(blank=True, default='', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='apartment',
            name='image4Text',
            field=models.CharField(blank=True, default='', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='apartment',
            name='image5Text',
            field=models.CharField(blank=True, default='', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='apartment',
            name='image6Text',
            field=models.CharField(blank=True, default='', max_length=50, null=True),
        ),
    ]
