# Generated by Django 2.1.2 on 2020-01-15 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0015_auto_20200115_0123'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='bodytext2',
            field=models.TextField(blank=True, verbose_name='Page Content'),
        ),
        migrations.AddField(
            model_name='page',
            name='menuTitle',
            field=models.CharField(blank=True, default='', max_length=20, null=True),
        ),
    ]
