# Generated by Django 2.1.2 on 2020-01-23 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0017_page_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='description',
            field=models.TextField(blank=True, default='', null=True, verbose_name='Page Content'),
        ),
    ]
