# Generated by Django 2.1.2 on 2020-01-24 01:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0018_auto_20200123_0243'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='apartment',
            name='serviceName',
        ),
    ]
