# Generated by Django 2.1.2 on 2020-01-24 01:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0019_remove_apartment_servicename'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TypeService',
        ),
    ]
